# Generated by Django 2.2.6 on 2019-10-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tbl_data_set',
            },
        ),
    ]
